name: lambda_trigger

on:
  workflow_dispatch:

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --function-name TriggerGitHubActions \
            --payload '{"key":"value"}' \
            --cli-binary-format raw-in-base64-out \
            out.json
          cat out.json