name: lambda_trigger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --function-name TriggerGitHubActions \
            --payload '{"someKey":"someValue"}' \
            --cli-binary-format raw-in-base64-out \
            out.json

          cat out.json
