name: Data Quality Check  # Workflow name

on: [push, pull_request]  # Run on every push and pull request

jobs:
  validate-data:
    runs-on: ubuntu-latest  # Use GitHub's Ubuntu VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Fetch repo files

      - name: Install R
        uses: r-lib/actions/setup-r@v2  # Install R on the VM
        with:
          r-version: '4.2'  # Specify R version

      - name: Run Data Quality Check
        run: Rscript data/data_checks.R  # Run the R script

      - name: Upload Subset Data
        uses: actions/upload-artifact@v4  # Save subset CSV for download
        with:
          name: subset-example
          path: data/subset_example.csv