name: S3 data fetch

on: [push, pull_request]  # Runs on push and PRs

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest  # Uses GitHub's virtual machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Fetches repo files

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli  # Installs AWS CLI on GitHub runner

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Fetch Data from S3
        run: |
          mkdir -p data
          aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.S3_FILE_PATH }} data/example.csv
          ls -lh data/  # Verify file is downloaded

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Run Data Checks
        run: Rscript R/data_checks.R  # Runs your script

      - name: Upload Processed Data as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: subset-example
          path: data/subset_example.csv