name: S3 Data Fetch & Process

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'S3 Bucket Name'
        required: true
      file:
        description: 'S3 File Path'
        required: true

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Fetch Data from S3
        run: |
          mkdir -p data
          aws s3 cp s3://${{ github.event.inputs.bucket }}/${{ github.event.inputs.file }} data/example.csv
          ls -lh data/

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Run Data Processing
        run: Rscript R/data_checks.R

      - name: Upload Processed Data as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: data/subset_example.csv